### ISSUE TITLE
Python packages version confit

### ISSUE THREAD

**Issue by BrycesWang** [titania7777/PCA-CBVR#1]
When I run your project, I do not know your environment. I install package but is not same with your version.

For example, when I run the code but throw Exception with follow in FeatureExtractor line 105(execute model_manager.get_encoder func):
A load persistent id instruction was encountered, but no persistent_load function was specified.

So, could you give your packages version with requirement.txt or other way？
Thank You!

**Comment by titania7777** [comment]
Hi @wang836564944 Sorry for the late reply.
I uploaded the requirement.txt file to this repository and finished the test on the new anaconda environment with python 3.8.
I hope this answer helps your works : )

**Comment by BrycesWang** [comment]
Thank you very much! This helped me a lot.
