### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by eveleslie** [titania7777/PCA-CBVR#2]
Hi, your code is very clean and concise, which helps me a lot！
But did you find that the test-set and the train-set in the dataset have cross-categories between each other?
This classification doesn't seem to fit the rules of few shot action recognition....

**Comment by titania7777** [comment]
Hi @eveleslie, thank you for having an interest in this work.

I provided a few-shot label only for UCF101, But there are no cross-categories between train and val(not test).

[UCF101 labels](https://www.dropbox.com/s/j4brxpdcqsp848n/ucf101_labels.zip)
labels/custom/categorical -> (for classification task)
labels/custom/fewshot -> (for few-shot task)

### Few-Shot Categories
**train(71 categories)**: ['ApplyEyeMakeup', 'ApplyLipstick', 'BabyCrawling', 'BalanceBeam', 'BandMarching', 'BaseballPitch', 'Basketball', 'BaskeetBowling', 'CuttingInKitchen', 'Diving', 'Drumming', 'Fencing', 'FieldHockeyPenalty', 'FloorGymnastics', 'FrisbeeCatch', 'FrontCrawl', 'GolfSwing', 'HeadMassage', 'HighJump', 'HorseRace', 'HulaHoop', 'JavelinThrow', 'JugglingBalls', 'JumpingJack', 'JumpRope', 'Kayaking', 'Knitting', 'LongJump', 'MilitaryParade', 'Mixing', 'MoppingFloor', 'ParallelBars', 'PizzaTossing', 'PlayingCello', 'PlayingDhol', 'PlayingFlute', 'PlayingGuitar', 'PlayingPiano', 'PlayingSitar', 'PlayingTabla', 'PlayingViolin', 'PoleVault', 'PommelHorse', 'Punch', 'Rafting', 'RockClimbingIndoor', 'SalsaSpin', 'ShavingBeard', 'SkateBoarding', 'SkyDiving', 'SoccerPenalty', 'StillRings', 'SumoWrestling', 'Surfing', 'Swing', 'TableTennisShot', 'TaiChi', 'ThrowDiscus', 'TrampolineJumping', 'Typing', 'UnevenBars', 'WalkingWithDog', 'WallPushups']

**val(30 categories)**: ['Archery', 'Billiards', 'BlowDryHair', 'BodyWeightSquats', 'BoxingPunchingBag', 'BreastStroke', 'BrushingTeeth', 'CricketShot', 'Haircut', 'Hammering', 'HammerThrow', 'HandstandPushups', 'HandstandWalking', 'HorseRiding', 'IceDancing', 'Lunges', 'Nunchucks', 'PlayingDaf', 'PullUps', 'PushUps', 'RopeClimbing', 'Rowing', 'Shotput', 'Skiing', 'Skijet', 'SoccerJuggling', 'TennisSwing', 'VolleyballSpiking', 'WritingOnBoard', 'YoYo']

Please tell me more detailed things if this answer was not helpful.

**Comment by eveleslie** [comment]
Hi!
I'm sorry I misread the dataset, I only downloaded the labels for hmdb51, I thought the folder 'categorical' was also for the FEW SHOT task.
Thanks a lot for your reply!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "titania7777/PCA-CBVR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 中午11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [titania7777/PCA-CBVR] About Dataset (Issue #2)





 
Hi @eveleslie, thank you for having an interest in this work.
 
I provided a few-shot label only for UCF101, But there are no cross-categories between train and val(not test).
 
UCF101 labels
 labels/custom/categorical -&gt; (for classification task)
 labels/custom/fewshot -&gt; (for few-shot task)
 
Few-Shot Categories
 
train(71 categories): ['ApplyEyeMakeup', 'ApplyLipstick', 'BabyCrawling', 'BalanceBeam', 'BandMarching', 'BaseballPitch', 'Basketball', 'BaskeetBowling', 'CuttingInKitchen', 'Diving', 'Drumming', 'Fencing', 'FieldHockeyPenalty', 'FloorGymnastics', 'FrisbeeCatch', 'FrontCrawl', 'GolfSwing', 'HeadMassage', 'HighJump', 'HorseRace', 'HulaHoop', 'JavelinThrow', 'JugglingBalls', 'JumpingJack', 'JumpRope', 'Kayaking', 'Knitting', 'LongJump', 'MilitaryParade', 'Mixing', 'MoppingFloor', 'ParallelBars', 'PizzaTossing', 'PlayingCello', 'PlayingDhol', 'PlayingFlute', 'PlayingGuitar', 'PlayingPiano', 'PlayingSitar', 'PlayingTabla', 'PlayingViolin', 'PoleVault', 'PommelHorse', 'Punch', 'Rafting', 'RockClimbingIndoor', 'SalsaSpin', 'ShavingBeard', 'SkateBoarding', 'SkyDiving', 'SoccerPenalty', 'StillRings', 'SumoWrestling', 'Surfing', 'Swing', 'TableTennisShot', 'TaiChi', 'ThrowDiscus', 'TrampolineJumping', 'Typing', 'UnevenBars', 'WalkingWithDog', 'WallPushups']
 
val(30 categories): ['Archery', 'Billiards', 'BlowDryHair', 'BodyWeightSquats', 'BoxingPunchingBag', 'BreastStroke', 'BrushingTeeth', 'CricketShot', 'Haircut', 'Hammering', 'HammerThrow', 'HandstandPushups', 'HandstandWalking', 'HorseRiding', 'IceDancing', 'Lunges', 'Nunchucks', 'PlayingDaf', 'PullUps', 'PushUps', 'RopeClimbing', 'Rowing', 'Shotput', 'Skiing', 'Skijet', 'SoccerJuggling', 'TennisSwing', 'VolleyballSpiking', 'WritingOnBoard', 'YoYo']
 
Please tell me more detailed things if this answer was not helpful.

**Comment by titania7777** [comment]
Oh, I apologize for the confusion.
Now I mentioned in 'PCA-CVBR/DB/README.md' clearly, and I will close this issue, thank you : )
